# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '通讯录' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 0.30.0.beta2'
  # Pods for 通讯录

end
